### ISSUE TITLE
Where to pass OAuth 2.0 ID ?

### ISSUE THREAD

**Issue by ramsmart-inno** [dev-juyoung/Fitness#3]

**Comment by dev-juyoung** [comment]
@ramsmart-inno 

Hi. Thank you for your interest in the Fitness plugin.

The OAuth 2.0 Client ID is not passed programmatically.
As you can see from the link below, this is one of the steps to enable the Google Fitness API.

https://developers.google.com/fit/android/get-started

If you are answered, please leave a reaction.
We will keep the issue open until there is a reaction.
