### ISSUE TITLE
Fitness plugin is not compatible in iOS

### ISSUE THREAD

**Issue by javiermelobodytech** [dev-juyoung/Fitness#7]
When i try to build my iOS project with the version 1.0.1, i get the following error.

[!] CocoaPods could not find compatible versions for pod "fitness":
  In Podfile:
    fitness (from `.symlinks/plugins/fitness/ios`)

Specs satisfying the `fitness (from `.symlinks/plugins/fitness/ios`)` dependency were found, but they required a higher minimum deployment target.

Thanks!

**Comment by dev-juyoung** [comment]
@javiermelobodytech 
What is the current development target version set in the iOS project and the MinimumOSVersion in AppFrameworkInfo.plist?

Fitness plugin supports iOS 11.0 or higher.

**Comment by dev-juyoung** [comment]
@javiermelobodytech 
Is the same thing happening now?
If there is no further update, the issue will be closed.

**Comment by javiermelobodytech** [comment]
Nop, now is compatible thanks!!!
