### ISSUE TITLE
Android Permission not being granted to Google Fit

### ISSUE THREAD

**Issue by mihir-chauhan** [dev-juyoung/Fitness#8]
Hi,

Thanks for making such a useful plugin for getting Health Kit and Google Fit data!

When I tried to follow the steps and create the OAuth ID and set up the code to request permission, it seems to be always giving this:

```[hasPermission]::false```

It pops up a window to log into an account and when I click it, it says:

```
I/flutter (10292): [hasPermission]::false
I/flutter (10292): [requestPermission]::false
```

The device does have Google Fit installed and Internet access.

Please let me know what I am doing wrong. Thanks!

**Comment by mihir-chauhan** [comment]
Just to note: I did not test iOS yet...

**Comment by dev-juyoung** [comment]
@mihir-chauhan 
Thanks for using my plugin.
Can you send me the source code so I can reproduce the problem?

**Comment by mihir-chauhan** [comment]
Hi @dev-juyoung 
Thanks for the reply.

I am actually trying out your example project in this repository. It just shows the Google sign in and then when I look at the Run Console, it prints false for hasPermission and requestPermission.

![screenshot](https://user-images.githubusercontent.com/39073758/120395221-7de10700-c2e9-11eb-81bc-96bb99536804.PNG)

**Comment by mihir-chauhan** [comment]
Hi @dev-juyoung 

I was able to debug the problem and it looks like I had to run in --release mode for it to work properly. Before I was defaulting to debug build. Thank you!

**Comment by dev-juyoung** [comment]
Hi @mihir-chauhan 

I'll update it later to make it executable even in debug mode.
Thanks for your interest in my plugin.
